layout_spectrum: 0.07714743
typography_spectrum: 0.7688668
color:
  saturation: 0.4083843
  lightness: 0.9220096
  brandStrength: 0.516129
  brandColors:
    - '#FFFFFF'
    - '#0C0E24'
    - '#CDB176'
    - '#466500'
    - '#083F9F'
  rhythmicContrast: 0.7748704
name: 'Health&Go'
