layout_spectrum: 0.07714743
typography_spectrum: 0.6057348
color:
  saturation: 0
  lightness: 0.5501792
  brandStrength: 0.516129
  brandColors:
    - '#FFFFFF'
    - '#0C0E24'
    - '#CDB176'
    - '#466500'
    - '#083F9F'
  rhythmicContrast: 0.08781362
name: 'Health&Go'
