layout_spectrum: 0.07714743
color:
  saturation: 0.9229391
  lightness: 0.6326165
  brandStrength: 0.516129
  brandColors:
    - '#FFFFFF'
    - '#0C0E24'
    - '#CDB176'
    - '#466500'
    - '#083F9F'
  rhythmicContrast: 0.7748704
typography_spectrum: 0.7688668
name: 'Health&Go'
